# -*- generated by 1.0.12 -*-
import da
PatternExpr_325 = da.pat.TuplePattern([da.pat.ConstantPattern('successor'), da.pat.FreePattern('query'), da.pat.FreePattern('succ_node')])
PatternExpr_347 = da.pat.TuplePattern([da.pat.ConstantPattern('result'), da.pat.FreePattern('query'), da.pat.FreePattern('result'), da.pat.FreePattern('authority')])
_config_object = {}
import logging
import random
import time
from hash_func import hash_func

class Client(da.DistProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([da.pat.EventPattern(da.pat.ReceivedEvent, '_ClientReceivedEvent_0', PatternExpr_325, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._Client_handler_324]), da.pat.EventPattern(da.pat.ReceivedEvent, '_ClientReceivedEvent_1', PatternExpr_347, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._Client_handler_346])])

    def setup(self, client_process, m, node_tuples, website, **rest_487):
        super().setup(client_process=client_process, m=m, node_tuples=node_tuples, website=website, **rest_487)
        self._state.client_process = client_process
        self._state.m = m
        self._state.node_tuples = node_tuples
        self._state.website = website
        self._state.client_process = self._state.client_process
        self._state.m = self._state.m
        self._state.node_tuples = self._state.node_tuples
        self._state.website = self._state.website
        self._state.query_count = 0
        self._state.start_times = {}
        self._state.end_times = {}
        self._state.resolution_latencies = set()
        self._state.hops = 0
        self._state.sleep_time = 0
        self._state.names = []

    def run(self):
        self.output(self._state.client_process, ' has been started.')
        for name in self._state.website:
            query = self.create_query(name)
            self.resolve(query)
        super()._label('_st_label_269', block=False)
        _st_label_269 = 0
        while (_st_label_269 == 0):
            _st_label_269 += 1
            if False:
                _st_label_269 += 1
            else:
                super()._label('_st_label_269', block=True)
                _st_label_269 -= 1

    def resolve(self, query):
        starting_node_tuple = random.choice(self._state.node_tuples)
        self._state.query_count += 1
        self._state.start_times[query['request_id']] = time.time()
        self.send(('find_successor', query), to=starting_node_tuple[1])
        self.output('Sent find_successor message for query: {q} to {node}'.format(q=query, node=starting_node_tuple))
        super()._label('_st_label_314', block=False)
        _st_label_314 = 0
        while (_st_label_314 == 0):
            _st_label_314 += 1
            if (query['request_id'] in self._state.end_times):
                _st_label_314 += 1
            else:
                super()._label('_st_label_314', block=True)
                _st_label_314 -= 1

    def create_query(self, name):
        query = {'website': name, 'hash_val': hash_func(name, self._state.m), 'request_id': self.obtain_request_id(), 'client_process': self._state.client_process, 'hops': self._state.hops, 'hops_names': self._state.names}
        return query

    def obtain_request_id(self):
        return ((str(self._state.client_process) + '-') + str(self._state.query_count))

    def _Client_handler_324(self, query, succ_node):
        self.send(('get', query), to=succ_node[1])
        self.output('Sent get to: ', succ_node)
    _Client_handler_324._labels = None
    _Client_handler_324._notlabels = None

    def _Client_handler_346(self, query, result, authority):
        self._state.end_times[query['request_id']] = time.time()
        self.output('Result of query for {query} = {ipaddr}'.format(query=query['website'], ipaddr=result))
        self._state.resolution_latencies.add((self._state.end_times[query['request_id']] - self._state.start_times[query['request_id']]))
        self.output('{website}, {TotalTime}, {hops}, {nodes}'.format(website=query['website'], hops=query['hops'], TotalTime=int(round(((self._state.end_times[query['request_id']] - self._state.start_times[query['request_id']]) * 1000), 0)), nodes=query['hops_names']), level=logging.DEBUG)
    _Client_handler_346._labels = None
    _Client_handler_346._notlabels = None
